version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - yarn
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - yarn build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - dist/index.js
    - dist/target.zip
